package jobkit

//go:generate go run ../cmd/bindata/main.go --ignore="\.DS_Store" -o static/static.go -p static ./_static/...
//go:generate go run ../cmd/bindata/main.go --ignore="\.DS_Store" -o views/views.go -p views ./_views/...
