version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/blend/jobkit
    steps:
      - checkout
      - run:
          name: ci
          command: make ci
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash) -X fix -f coverage.txt
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/blend/jobkit
    steps:
      - checkout
      - run:
          name: s3upload
          command: make upload

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
