title: "Example Job Manager"

web:
  bindAddr: ":8080"

logger:
  flags: ["all"]

jobs:
  - name: "hello world"
    labels:
      kind: "parameterized"
      team: "bailey"
    schedule: "*/10 * * * * *"
    historyEnabled: true
    historyPersistenceEnabled: false
    parameters:
      - name: "MESSAGE"
        label: "Message"
        placeholder: "put a message here"
        value: "THIS IS A TEST"
        required: true
      - name: "ENVIRONMENT"
        label: "Environment"
        value: "sandbox"
        options:
          - value: "sandbox"
            text: "Sandbox"
          - value: "production"
            text: "Production"
    exec:
      - "echo"
      - "${MESSAGE}"
      - "${ENVIRONMENT}"
      - "ran successfully!"
