title: "Example Job Manager"

web:
  bindAddr: ":8080"

logger:
  flags: ["all"]

jobs:
  - name: "hello world"
    labels:
      kind: "static"
      team: "bailey"
    schedule: "*/5 * * * * *"
    historyDisabled: false
    historyMaxCount: 64
    exec: ["echo", "'hello world!'"]

  - name: "parameters test"
    labels:
      kind: "parameterized"
      team: "bailey"
    schedule: "*/30 * * * * *"
    historyDisabled: false
    historyMaxCount: 32
    parameters:
      - name: "MESSAGE"
        label: "Message"
        placeholder: "put a message here"
        value: "THIS IS A TEST"
        required: true
      - name: "ENVIRONMENT"
        label: "Environment"
        value: "sandbox"
        options:
          - value: "sandbox"
            text: "Sandbox"
          - value: "production"
            text: "Production"
    exec:
      - "sh"
      - "_examples/long.sh"
      - "${MESSAGE}"
      - "${ENVIRONMENT}"
