title: "Example Job Manager"

web:
  bindAddr: ":8080"

logger:
  flags: ["all"]

jobs:
  - name: "hello world"
    labels:
      team: "bailey"
      sla: false
    schedule: "@every 60s"
    historyDisabled: false
    historyPersistenceDisabled: false
    notifications:
      retryWait: "5s"
      maxAttempts: 5
      onSuccess: true
      onError: true
      webhook:
        url: "http://localhost:8080/api/debug/error"
    exec:
      - "echo"
      - "hello"
      - "world"
